Реализована функция для запуска конкурентного пайплайна, состоящего из стейджей
nsmak/otus_hw pull request #6
Opened 2020-10-25 12:58 UTC by nsmak

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-10-28 17:27 UTC, kulti requested changes
В решение есть пара ошибок. Предлагаю поправить.

2020-10-28 17:27 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +					takeStream <- val
Если последующий стейдж уже вышел по done, то эта запись в канал навсегда зависнет.

2020-10-28 17:27 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +		return nil
Если вернуть nil, то чтение навсегда зависнет. Лучше возвращать закрытый канал.

Для случая, когда нет стейджей, мне кажется более логично пропустить все входные данные в выходные. В задании этот момент никак не указан, так что это можно не переделывать.

2020-10-28 19:37 UTC, nsmak commented
Исправил ошибки плюс, возможно, пограничную ситуация. Не знаю, имеет ли смысл и возможна ли ситуация, когда после закрытия done, данные могут продолжить приходить?

2020-10-29 08:16 UTC, kulti approved these changes
Спасибо за правки. ДЗ принято - 10/10.

> Не знаю, имеет ли смысл и возможна ли ситуация, когда после закрытия done, данные могут продолжить приходить?

Интересный вопрос. Думаю, раз done и in приходят снаружи, то эта ситуация забота того, кто запустил пайплайн. В продакшен-коде я бы добавил док-стринг к этому методу, где описал этот момент. Что-то вроде: "Note that after closing done channel ExecutePipeline may not read from in channel".

2020-10-29 09:04 UTC, nsmak commented
Спасибо большое!

2020-10-29 09:04 UTC, merged